const bbmons = ['boar bb',
                'wolf bb',
                'puppy bb',
                'big puppy bb',
                'lion bb',
                'panther bb',
                'based beast bb',
                'minotaur bb',
                'cat bb',
                'werewolf bb',
                'dragon bb',
                'bunny bb',
                'satyr bb',
                'angel bb',
                'dionysus bb',
                'owner bb',
                'the most handsome demon in all hell bb',
                'brother (older)',
                'brother (younger)',
                'boy (hero)',
                'entitled shota',
                'demon boy bb',
                'boy detective',
                'cherub bb',
                'soldier bb',
                'gamer bb',
                'writer bb',
                'lord grayston',
                'cool ben',
                'edgy bb',
                'coach bb',
                'dad bb',
                'doctor bb',
                'goblin bb',
                '(b)(p)orc bb',
                'goonbmon(-kun)',
                'pig bb',
                'horsebb',
                'catboy',
                'catboy streamer',
                'cowboy',
                'sergeant bbmon',
                'OBESEBMON',
                'spiritually obesebmon',
                'otaku virgin bb',
                'jazzpig',
                'truffle pig',
                'teapig',
                'bullywug (bully wully)',
                'catn*p cat',
                'catn*p cat (sober)',
                'boarnip boar',
                'lizardman bb (two cocks!)',
                'mpreg / lactating bb???',
                'obliquebmon',
                'rear admiral bbmon',
                'big mimiga',
                'catboy director',
                'boy ralts',
                'psychologically-minded bbmon',
                'catnipple cat',
                'child psychiatrist (he is a child)',
                'axilla villain',
                'shota with a gun', 
                'grimy 90s putto',
                'gamemaster bb',
                'emotional support / service pig',
                'medical orc',
                'rarity-stratified bunny boys',
                'mangy dog',
                'alpha the alphabet-learning horse ',
                'bwee the virgin goblin',
                'bhogar, resurrected goblin',
                'emperor catboy',
                'barkhide troll',
                'mudori the ox',
                'arms dealer shota',
                'shota ghostbuster',
                'catboy psychiatrist',
                'fourc the orc / fiorc the orc',
                'father brown (priest)',
                'little brown riding hood',
                '3/3 legendary enchantment toad bmon',
                'anurid brushhopper',
                'generous visitor jacking off',
                'french pervert collector bbmon',
                'pomo dog bbmon']

const ypmons = ['shy p',
                'science p',
                'angel p',
                'daughter p', 
                'domestic p',
                'healer p',
                'maid p',
                'gamer p',
                'athlete p',
                'boy yena',
                'pet p',
                'mage p',
                'goddess p',
                'fighter p',
                'centaur p',
                'mama yena',
                'sister yena (older)',
                'sister yena (younger)',
                'boar p',
                'rogue p',
                'spider p',
                'supreme leader', 
                'ypmon department',
                'bureaucrat’s daughter',
                'monkey p',
                'gyaru p',
                'chuuni p',
                'rational middle school yena',
                'lowly loli succubus p',
                '30 yo succubus p',
                'yp bot (ROB)',
                'love detective p',
                'orphan p',
                'meganekko',
                'ghost p',
                'neco arc',
                'chill girl',
                'cowgirl',
                'yenamine (ketamine yena)',
                'med student p',
                'office p',
                'autistic p',
                'insanepmon',
                'lieutenant ypmon',
                'streamer p',
                'goonpmon (pokemon trainer)',
                'me llamo miyamo ypmon',
                'milk delivery~ (milk truck p)',
                'blurrymon',
                'maturemoto',
                'rebellious imouto',
                'wiimouto',
                'emotional support cat', 
                'vampymon',
                'r*ghts pmon',
                'no r*ghts pmon',
                'nyang nyang nyong nyong dorong dorong mon',
                'azorius nyong nyong dorong dorong mon',
                'moiyong moiyong p',
                'yoi yoi mon (they like pies)',
                'adderall IR and adderall XR lolis',
                'clothes moth',
                'british p',
                'illiterate kino genius pmon',
                'big imp (literate)',
                'yenislav patroshka (russian p)',
                'girlfriend who once lived in brooklyn',
                'grasshopper mouse p',
                'philosophy grad student p (hegel)',
                'horizontal p',
                'medium imp',
                'cock-worshipping farmer ypmon',
                'star realms mesugaki',
                'social justice ypmon advocating for shota rights',
                'bratty p on a moncycle', 
                'literate imp p mon',
                'bratty cat (waitressing, fallen on hard times)',
                'mucuous devil pmon (blow your nose to summon)',
                'steel wool pmon',
                'damaged cake loli (scar)',
                'nimious babuina',
                'sayana the playboy marketing director',
                'yesinia, necromancer girl',
                'queen of small country',
                'dark elf shota slaver',
                'subbing general p',
                'strawberry and mint loli p',
                'kiss bot kill bot',
                'metamon (ditto)',
                'mute boy, the shadow p',
                'dark elf kitsune (dream shadow p)',
                'lucky imouto',
                'lucky cat',
                'moonfolk puzzlemaker',
                'nashi',
                'selesneya platpmon',
                'orzhov diamond p',
                'mythicc aggromon',
                'pepper the oni',
                'nipple harvester',
                'nyong nyong study study mon',
                'kashi, mouser (nashi but cat)']

let random_bb 
let random_yp

document.getElementById("rollButton").onclick = function(){

    random_bb = bbmons[Math.floor(Math.random() * bbmons.length)] 
    random_yp = ypmons[Math.floor(Math.random() * ypmons.length)]

    document.getElementById("bb").innerHTML = random_bb;
    document.getElementById("yp").innerHTML = random_yp;
}